apiVersion: v1
appVersion: "0.0.1"
description: A Helm chart for Samvera Oregon
name: oregon
version: 0.0.1
dependencies:
  - name: solr 
    version: 1.0.0
    repository: https://storage.googleapis.com/kubernetes-charts-incubator
  - name: redis
    version: 10.3.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
  - name: postgresql
    version: 8.1.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
