Metrics/AbcSize:
  Exclude:
    - 'app/indexers/oregon_digital/deep_indexing_service.rb'
    - 'app/controllers/hyrax/contact_form_controller.rb'
    - 'app/indexers/generic_indexer.rb'
    - 'app/forms/oregon_digital/forms/collection_form.rb'
    - 'app/models/concerns/oregon_digital/ability/work_show_ability.rb'
    - 'app/models/concerns/oregon_digital/ability/collection_ability.rb'
    - 'app/workers/fetch_graph_worker.rb'
    - 'lib/oregon_digital/triplestore.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/oregon_digital/controlled_vocabularies/subject.rb'
    - 'lib/oregon_digital/controlled_vocabularies/resource.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'
    - 'spec/support/helpers/session_helpers.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/concerns/oregon_digital/access_controls/visibility.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'
    - 'app/services/oregon_digital/file_set_derivatives_service.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*.rb'
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/oregon_digital/triplestore.rb'
    - 'lib/oregon_digital/controlled_vocabularies/subject.rb'
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'
    - 'app/renderers/hyrax/renderers/rights_statement_attribute_renderer.rb'
    - 'app/indexers/generic_indexer.rb'
    - 'app/models/concerns/oregon_digital/access_controls/visibility.rb'
    - 'app/helpers/hyrax/ability_helper.rb'
    - 'app/workers/fetch_graph_worker.rb'
    - 'lib/tasks/oregon_digital/create_full_metadata_work.rake'

Naming/AccessorMethodName:
  Exclude:
    - 'lib/oregon_digital/controlled_vocabularies/resource.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/users/omniauth_callbacks_controller_spec.rb'

Style/SymbolArray:
  Exclude:
    - 'app/models/user.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/oregon_digital/oembeds_controller_spec.rb'
    - 'spec/forms/oregon_digital/forms/collection_form_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/controllers/oregon_digital/oembeds_controller_spec.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/workers/fetch_graph_worker_spec.rb'