Metrics/LineLength:
  # Ignore comment lines that may being with spaces
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/oregon_digital/oembeds_controller.rb'
    - 'app/forms/hyrax/audio_form.rb'
    - 'app/forms/hyrax/document_form.rb'
    - 'app/forms/hyrax/generic_form.rb'
    - 'app/forms/hyrax/image_form.rb'
    - 'app/forms/hyrax/video_form.rb'
    - 'app/models/ability.rb'
    - 'app/models/concerns/oregon_digital/document_metadata.rb'
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'
    - 'app/models/concerns/oregon_digital/image_metadata.rb'
    - 'app/models/concerns/oregon_digital/video_metadata.rb'
    - 'app/models/file_set.rb'
    - 'app/models/search_builder.rb'
    - 'app/models/solr_document.rb'
    - 'app/presenters/hyrax/document_presenter.rb'
    - 'app/presenters/hyrax/generic_presenter.rb'
    - 'app/presenters/hyrax/image_presenter.rb'
    - 'app/presenters/hyrax/video_presenter.rb'
    - 'app/search_builders/oregon_digital/oembed_search_builder.rb'
    - 'app/services/hyrax/derivative_service.rb'
    - 'app/services/oregon_digital/file_set_derivatives_service.rb'
    - 'config/application.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/staging.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/hydra_config.rb'
    - 'config/initializers/hyrax.rb'
    - 'config/initializers/mailboxer.rb'
    - 'config/initializers/redis_config.rb'
    - 'config/initializers/sidekiq.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/routes.rb'
    - 'lib/oregon_digital/triple_powered_properties/has_url_validator.rb'
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'
    - 'lib/oregon_digital/triple_powered_properties/triple_powered_form.rb'
    - 'lib/oregon_digital/triple_powered_properties/triplestore.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_indexer.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'
    # allow all specs to have long lines, these don't really need fixing
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/oregon_digital/triple_powered_properties/triplestore.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'
    - 'spec/support/helpers/session_helpers.rb'

# 35 offenses
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/oregon_digital/oembeds_controller.rb'
    - 'app/forms/hyrax/document_form.rb'
    - 'app/forms/hyrax/image_form.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/hyrax_helper.rb'
    - 'app/helpers/oregon_digital/oembed_helper.rb'
    - 'app/indexers/audio_indexer.rb'
    - 'app/indexers/document_indexer.rb'
    - 'app/indexers/generic_indexer.rb'
    - 'app/indexers/image_indexer.rb'
    - 'app/indexers/video_indexer.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/ability.rb'
    - 'app/models/application_record.rb'
    - 'app/models/audio.rb'
    - 'app/models/collection.rb'
    - 'app/models/document.rb'
    - 'app/models/file_set.rb'
    - 'app/models/generic.rb'
    - 'app/models/image.rb'
    - 'app/models/user.rb'
    - 'app/models/video.rb'
    - 'app/models/concerns/oregon_digital/document_metadata.rb'
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'
    - 'app/models/concerns/oregon_digital/image_metadata.rb'
    - 'app/models/concerns/oregon_digital/video_metadata.rb'
    - 'app/models/qa.rb'
    - 'app/models/qa/local_authority_entry.rb'
    - 'app/models/search_builder.rb'
    - 'app/models/solr_document.rb'
    - 'app/models/user.rb'
    - 'app/presenters/hyrax/document_presenter.rb'
    - 'app/presenters/hyrax/generic_presenter.rb'
    - 'app/presenters/hyrax/image_presenter.rb'
    - 'app/presenters/hyrax/video_presenter.rb'
    - 'app/renderers/oembed_attribute_renderer.rb'
    - 'app/services/hyrax/derivative_service.rb'
    - 'app/services/oregon_digital/file_set_derivatives_service.rb'
    - 'app/services/oregon_digital/oembed_service.rb'
    - 'config/application.rb'
    - 'lib/oregon_digital.rb'
    - 'lib/oregon_digital/triple_powered_properties/has_url_validator.rb'
    - 'lib/oregon_digital/triple_powered_properties/triple_powered_form.rb'
    - 'lib/oregon_digital/triple_powered_properties/triplestore.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_indexer.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/oregon_digital/oembeds_controller_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/controllers/oregon_digital/oembeds_controller_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'config/initializers/hyrax.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/users/omniauth_callbacks_controller_spec.rb'

Style/SymbolArray:
  Exclude:
    - 'app/models/user.rb'
