require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'build/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/**/*'
    - 'app/presenters/hyrax/file_set_presenter.rb'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*.rb'
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'
    - 'app/models/concerns/oregon_digital/video_metadata.rb'
    - 'app/models/concerns/oregon_digital/document_metadata.rb'
    - 'app/models/concerns/oregon_digital/image_metadata.rb'


Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/views/**/*'
    - 'spec/config/initializers/**/*'
    - 'spec/tasks/**/*'

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

FactoryBot/FactoryClassName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Migration/DepartmentName:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/helpers/oregon_digital/citations_behaviors/formatters/wiki_formatter_spec.rb'

RSpec/SubjectStub:
  Exclude:
    - 'spec/helpers/oregon_digital/citations_behaviors/formatters/wiki_formatter_spec.rb'