Metrics/AbcSize:
  Exclude:
    - 'app/indexers/oregon_digital/deep_indexing_service.rb'
    - 'app/controllers/hyrax/contact_form_controller.rb'
    - 'app/indexers/generic_indexer.rb'
    - 'app/forms/oregon_digital/forms/collection_form.rb'
    - 'app/models/concerns/oregon_digital/ability/work_show_ability.rb'
    - 'app/models/concerns/oregon_digital/ability/collection_ability.rb'
    - 'app/workers/fetch_graph_worker.rb'
    - 'app/workers/fetch_failed_graph_worker.rb'
    - 'lib/oregon_digital/triplestore.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/oregon_digital/controlled_vocabularies/subject.rb'
    - 'lib/oregon_digital/controlled_vocabularies/resource.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'
    - 'spec/support/helpers/session_helpers.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/oregon_digital/triplestore.rb'
    - 'lib/oregon_digital/controlled_vocabularies/subject.rb'
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'
    - 'app/renderers/hyrax/renderers/rights_statement_attribute_renderer.rb'
    - 'app/indexers/generic_indexer.rb'
    - 'app/models/concerns/oregon_digital/access_controls/visibility.rb'
    - 'app/helpers/hyrax/ability_helper.rb'
    - 'app/workers/fetch_graph_worker.rb'
    - 'app/workers/fetch_failed_graph_worker.rb'
    - 'lib/tasks/oregon_digital/create_full_metadata_work.rake'
