Metrics/LineLength:
  # Ignore comment lines that may begin with spaces
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'app/controllers/oregon_digital/oembeds_controller.rb'
    - 'app/models/concerns/oregon_digital/document_metadata.rb'
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'
    - 'app/models/concerns/oregon_digital/image_metadata.rb'
    - 'app/models/concerns/oregon_digital/video_metadata.rb'
    - 'spec/**/*'
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'
    - 'lib/hyrax/controlled_vocabularies/location.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/indexers/oregon_digital/deep_indexing_service.rb'
    - 'app/controllers/hyrax/contact_form_controller.rb'
    - 'app/indexers/generic_indexer.rb'
    - 'lib/oregon_digital/triple_powered_properties/triplestore.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'
    - 'spec/support/helpers/session_helpers.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/oregon_digital/triple_powered_properties/inputs/triple_powered_property_input.rb'
    - 'lib/oregon_digital/triple_powered_properties/work_behavior.rb'
    - 'lib/tasks/oregon_digital/csv_ingest.rake'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/users/omniauth_callbacks_controller_spec.rb'

Style/SymbolArray:
  Exclude:
    - 'app/models/user.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/oregon_digital/oembeds_controller_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/controllers/oregon_digital/oembeds_controller_spec.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'