require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'build/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*.rb'
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/oregon_digital/generic_metadata.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/views/**/*'
    - 'spec/config/initializers/**/*'
    - 'spec/tasks/**/*'

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

# FactoryBot 5 will require dynamic definition, so we should allow it.
FactoryBot/StaticAttributeDefinedDynamically:
  Enabled: false
