version: '2'

volumes:
  ? fcrepo
  ? solr
  ? db
  ? redis
  ? app

networks:
  ? external
  ? internal

services:
  solr:
    image: solr
    expose:
      - 8983
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/conf:/opt/solr/server/solr/configsets/_default/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ${RAILS_ENV}
    networks:
      ? internal

  fcrepo:
    image: cbeer/fcrepo4:4.7
    expose:
      - 8080
    volumes:
      - fcrepo:/data
    environment:
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    networks:
      ? internal

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      ? internal

  app:
    build: .
    environment:
      - ACTIVE_JOB_QUEUE_ADAPTER=sidekiq
      - DATABASE_URL=postgresql://postgres@db/postgres
      - FEDORA_URL=http://fcrepo:8080/fcrepo/rest
      - FITS_PATH=/opt/fits-1.0.5/fits.sh
      - RAILS_CACHE_STORE_URL=memcache
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - REDIS_HOST=redis
      - SECRET_KEY_BASE=asdf
      - SOLR_URL=http://solr:8983/solr/${RAILS_ENV}
    volumes:
      - .:/data
      - app:/data/tmp/uploads
    networks:
      ? internal

  web:
    extends: app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - memcache
      - db_migrate
    expose:
      - 3000

  workers:
    extends: app
    command: bundle exec sidekiq
    environment:
      - SETTINGS__FITS_PATH=/opt/fits-1.0.5/fits.sh
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - initialize_app
      - db_migrate

  initialize_app:
    extends: app
    restart: on-failure
    command: echo 'Not using Zookeeper'

  db_migrate:
    extends: app
    restart: on-failure
    command: bundle exec rails db:migrate
    depends_on:
      - db

  lb:
    image: dockercloud/haproxy:1.5.3
    links:
      - web
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # You must uncomment this line if and only if you are running docker-machine
      # - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    networks:
      ? internal
      ? external

  redis:
    image: redis:3
    command: redis-server
    volumes:
      - redis:/data
    networks:
      ? internal

  memcache:
    image: memcached
    networks:
      ? internal
