version: '2'

networks:
  ? internal
  ? external

services:
  solr:
    image: solr
    expose:
      - 8983
    volumes:
      - ./solr/conf:/opt/solr/server/solr/configsets/_default/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test
    networks:
      ? internal

  fcrepo:
    image: cbeer/fcrepo4:4.7
    expose:
      - 8080
    environment:
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    networks:
      ? internal

  db:
    image: postgres
    networks:
      ? internal

  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
      - ./spec/fixtures:/data/spec/fixtures
    ports:
      - '4444:4444'
    networks:
      ? internal

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      - FEDORA_URL=http://fcrepo:8080/fcrepo/rest
      - FITS_PATH=/opt/fits-1.0.5/fits.sh
      - RAILS_ENV=test
      - RDS_DB_NAME=postgres
      - RDS_HOSTNAME=db
      - RDS_PASSWORD=postgres
      - RDS_PORT='5432'
      - RDS_USERNAME=postgres
      - REDIS_HOST=redis
      - SECRET_KEY_BASE=asdf
      - SELENIUM_HUB_URL=http://chrome:4444/wd/hub
      - SOLR_URL=http://solr:8983/solr/test
    volumes:
      - .:/data
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - db
      - fcrepo
      - redis
      - solr
    networks:
      ? internal
      ? external

  redis:
    image: redis:3
    command: redis-server
    networks:
      ? internal
