---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "oregon.fcrepo.name" . }}
  labels:
    app: {{ template "oregon.name" . }}
    chart: {{ template "oregon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: fcrepo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fcrepo.storage.size }}
  {{- if .Values.fcrepo.storage.className }}
  storageClassName: "{{ .Values.fcrepo.storage.ClassName }}"
  {{- end }}
