---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "oregon.setup.name" . }}
  labels:
    app: {{ template "oregon.name" . }}
    chart: {{ template "oregon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: {{ template "oregon.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      {{- if .Values.rails.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.rails.imagePullSecrets }}
      {{- end }}
      initContainers:
        - name: check-solr-ready
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "response=0 && until [ $response == 200 ]; do response=$(curl --write-out %{http_code} --silent --output /dev/null $(echo $SOLR_BASE_URL)/admin/collections?action=LIST); echo Response is $response; sleep 5; done;"
          envFrom:
            - configMapRef:
                name: {{ template "oregon.rails-env.name" . }}
      containers:
        - name: setup
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "ruby ./chart/bin/solr-setup.rb && bundle exec rails db:migrate && bundle exec rails assets:precompile && build/firstrun.sh"
          envFrom:
            - configMapRef:
                name: {{ template "oregon.rails-env.name" . }}
            - secretRef:
                name: {{ template "oregon.rails-env.name" . }}
