---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "oregon.web.name" . }}-in
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    hosts:
      - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "oregon.web.name" . }}
          servicePort: 3000
