name: Accessibility
description: For accessibility related issues
title: "[A11y] "
labels: [Accessibility, Features]
body:
  - type: dropdown
    attributes:
      label: Operating System
      description: What OS did you test with?
      multiple: false
      options:
        - MacOS
        - Windows
        -  Linux
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Browser
      description: What browser did you test with?
      multiple: false
      options:
        - Firefox
        - Edge
        - Safari
        - Chrome
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected page
      description: Which page was the issue found on?
      multiple: false
      options:
        - Homepage
        - Search
        - Work Show
        - Collection Show
        - Explore Collections
        - Advanced Search
        - Supporting (/contact, /help, etc)
        - Backend
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Admin user?
      description: Were you logged in as the admin user?
      multiple: false
      options:
        - Yes
        - No
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue Description
      description: "Please describe the WCAG failure or accessibility issue."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Fix
      description: "If applicable, how would you fix this issue?"
