admin_sets:
  - id: University_of_Oregon
    title: University of Oregon
    description: 'Works created, managed and administered by the University of Oregon.'
  - id: Oregon_State_University
    title: Oregon State University
    description: 'Works created, managed and administered by Oregon State University, not including materials administered by the Special Collections and Archives Research Center.'
  - id: SCARC_OSULP
    title: Special Collections and Archives Research Center, Oregon State University Libraries and Press
    description: 'Works created, managed and administered by the Special Collections and Archives Research Center, Oregon State University Libraries and Press.'
