admin_sets:
  - title: University of Oregon
    description: 'Works created, managed and administered by the University of Oregon.'
  - title: Oregon State University
    description: 'Works created, managed and administered by Oregon State University, not including materials administered by the Special Collections and Archives Research Center.'
  - title: Special Collections and Archives Research Center, Oregon State University Libraries and Press
    description: 'Works created, managed and administered by the Special Collections and Archives Research Center, Oregon State University Libraries and Press.'