crosswalk:
  - primary_set: oregondigital:aa-images
    admin_set_title: UO
  - primary_set: oregondigital:african-ephemera
    admin_set_title: UO
  - primary_set: oregondigital:alice-b-sheldon
    admin_set_title: UO
  - primary_set: oregondigital:angelus-studio
    admin_set_title: UO
  - primary_set: oregondigital:annual-cruise
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:arch-entourage
    admin_set_title: UO
  - primary_set: oregondigital:artists-books
    admin_set_title: UO
  - primary_set: oregondigital:braceros
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:building-or
    admin_set_title: UO
  - primary_set: oregondigital:chinavine
    admin_set_title: UO
  - primary_set: oregondigital:clarence-andrews
    admin_set_title: UO
  - primary_set: oregondigital:columbia-gorge
    admin_set_title: OSU
  - primary_set: oregondigital:colver-family
    admin_set_title: UO
  - primary_set: oregondigital:corvallis-flood
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:corvallis-images
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:cw-furlong
    admin_set_title: UO
  - primary_set: oregondigital:daily-barometer
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:daily-emerald
    admin_set_title: UO
  - primary_set: oregondigital:dan-powell
    admin_set_title: UO
  - primary_set: oregondigital:dissociation
    admin_set_title: UO
  - primary_set: oregondigital:doris-ulmann
    admin_set_title: UO
  - primary_set: oregondigital:electric-studio
    admin_set_title: UO
  - primary_set: oregondigital:ellis-fuller-lawrence
    admin_set_title: UO
  - primary_set: oregondigital:ellmaker-family
    admin_set_title: UO
  - primary_set: oregondigital:fairbanks
    admin_set_title: OSU
  - primary_set: oregondigital:finley-bohlman
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:florence-hartshorn
    admin_set_title: UO
  - primary_set: oregondigital:frazier-boutelle
    admin_set_title: UO
  - primary_set: oregondigital:gb-warner
    admin_set_title: UO
  - primary_set: oregondigital:gb-warner-nosatsu
    admin_set_title: UO
  - primary_set: oregondigital:gb-warner-papers-ua022
    admin_set_title: UO
  - primary_set: oregondigital:gbwarnerpapers
    admin_set_title: UO
  - primary_set: oregondigital:general-catalogs
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:gifford
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:grayson-mathews
    admin_set_title: UO
  - primary_set: oregondigital:gwilliams
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:herbarium
    admin_set_title: OSU
  - primary_set: oregondigital:illustrated-booklets
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:james-cloutier
    admin_set_title: UO
  - primary_set: oregondigital:jasr
    admin_set_title: UO
  - primary_set: oregondigital:joanna-russ
    admin_set_title: UO
  - primary_set: oregondigital:joel-palmer
    admin_set_title: UO
  - primary_set: oregondigital:john-bauguess
    admin_set_title: UO
  - primary_set: oregondigital:johnyeonarchdrawings
    admin_set_title: UO
  - primary_set: oregondigital:ken-gray
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:lchsa
    admin_set_title: OSU
  - primary_set: oregondigital:lee-drake
    admin_set_title: UO
  - primary_set: oregondigital:lee-moorhouse
    admin_set_title: UO
  - primary_set: oregondigital:lichens-pnw
    admin_set_title: OSU
  - primary_set: oregondigital:lowenstam
    admin_set_title: UO
  - primary_set: oregondigital:maic
    admin_set_title: UO
  - primary_set: oregondigital:mayo-methot-bogart
    admin_set_title: UO
  - primary_set: oregondigital:middle-east-water
    admin_set_title: OSU
  - primary_set: oregondigital:mountaingrove
    admin_set_title: UO
  - primary_set: oregondigital:mss-rb
    admin_set_title: UO
  - primary_set: oregondigital:ncu
    admin_set_title: UO
  - primary_set: oregondigital:nw-folklife
    admin_set_title: UO
  - primary_set: oregondigital:ocfrp
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:ohba
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:oimb
    admin_set_title: UO
  - primary_set: oregondigital:opal-whiteley
    admin_set_title: UO
  - primary_set: oregondigital:or-chinese-disinterment
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:or-latino-herit
    admin_set_title: UO
  - primary_set: oregondigital:orange-owl
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:oregon-multicultural-archives
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:oregon-state-yank
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:oregons-agricultural-progress
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:ormaps
    admin_set_title: UO
  - primary_set: oregondigital:osu-alumni-magazine
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-athletics
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-baseball
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-commencement-programs
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-department-histories
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-fact-book
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-historical-images
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-historical-publications
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-scarc
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-sports-media-guides
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-student-protest-underground-pubs
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-wwii-japanese-american-students
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:osu-yearbooks
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:percent-for-art
    admin_set_title: UO
  - primary_set: oregondigital:petrarch
    admin_set_title: UO
  - primary_set: oregondigital:quincy-scott
    admin_set_title: UO
  - primary_set: oregondigital:rockyshore93
    admin_set_title: OSU
  - primary_set: oregondigital:roy-c-andrews
    admin_set_title: UO
  - primary_set: oregondigital:rv-mills
    admin_set_title: UO
  - primary_set: oregondigital:schnitzer-nitrate
    admin_set_title: UO
  - primary_set: oregondigital:sheetmusic
    admin_set_title: UO
  - primary_set: oregondigital:siuslaw
    admin_set_title: OSU
  - primary_set: oregondigital:streamsurvey
    admin_set_title: OSU
  - primary_set: oregondigital:textile-and-apparel
    admin_set_title: OSU
  - primary_set: oregondigital:texts-data
    admin_set_title: UO
  - primary_set: oregondigital:the-manuscript
    admin_set_title: OSU SCARC
  - primary_set: oregondigital:uo-arch-photos
    admin_set_title: UO
  - primary_set: oregondigital:uo-athletics
    admin_set_title: UO
  - primary_set: oregondigital:uo-president
    admin_set_title: UO
  - primary_set: oregondigital:uo-stock-photos
    admin_set_title: UO
  - primary_set: oregondigital:uo-veterans
    admin_set_title: UO
  - primary_set: oregondigital:walter-bowman
    admin_set_title: UO
  - primary_set: oregondigital:western-waters
    admin_set_title: UO
  - primary_set: oregondigital:willis-dunagan
    admin_set_title: UO
