terms:
- id: "annotations"
  term: "annotations"
  active: true
- id: "index"
  term: "index"
  active: true
- id: "pageBreakMarkers"
  term: "pageBreakMarkers"
  active: true
- id: "pageNavigation"
  term: "pageNavigation"
  active: true
- id: "readingOrder"
  term: "readingOrder"
  active: true
- id: "structuralNavigation"
  term: "structuralNavigation"
  active: true
- id: "tableOfContents"
  term: "tableOfContents"
  active: true
- id: "taggedPDF"
  term: "taggedPDF"
  active: true
- id: "alternativeText"
  term: "alternativeText"
  active: true
- id: "audioDescription"
  term: "audioDescription"
  active: true
- id: "closedCaptions"
  term: "closedCaptions"
  active: true
- id: "describedMath"
  term: "describedMath"
  active: true
- id: "longDescription"
  term: "longDescription"
  active: true
- id: "openCaptions"
  term: "openCaptions"
  active: true
- id: "signLanguage"
  term: "signLanguage"
  active: true
- id: "transcript"
  term: "transcript"
  active: true
- id: "synchronizedAudioText"
  term: "synchronizedAudioText"
  active: true
- id: "timingControl"
  term: "timingControl"
  active: true
- id: "unlocked"
  term: "unlocked"
  active: true
- id: "ChemML"
  term: "ChemML"
  active: true
- id: "latex"
  term: "latex"
  active: true
- id: "latex-chemistry"
  term: "latex-chemistry"
  active: true
- id: "MathML"
  term: "MathML"
  active: true
- id: "MathML-chemistry"
  term: "MathML-chemistry"
  active: true
- id: "ttsMarkup"
  term: "ttsMarkup"
  active: true
- id: "highContrastAudio"
  term: "highContrastAudio"
  active: true
- id: "braille"
  term: "braille"
  active: true
- id: "tactileGraphic"
  term: "tactileGraphic"
  active: true
- id: "tactileObject"
  term: "tactileObject"
  active: true
- id: "none"
  term: "none"
  active: true
- id: "unknown"
  term: "unknown"
  active: true
