terms:
  - id: http://purl.org/dc/dcmitype/Collection
    term: Complex Object 
  - id: http://purl.org/dc/dcmitype/Dataset
    term: Dataset
  - id: http://purl.org/dc/dcmitype/Image
    term: Image
  - id: http://purl.org/dc/dcmitype/MovingImage
    term: Video
  - id: http://purl.org/dc/dcmitype/PhysicalObject
    term: Physical Object
  - id: http://purl.org/dc/dcmitype/Sound
    term: Audio
  - id: http://purl.org/dc/dcmitype/Text
    term: Text
