development:
  adapter: solr
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8983') %>/solr/development
test: &test
  adapter: solr
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8985') %>/solr/test
production:
  adapter: solr
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8080/solr/production') %>
staging:
  adapter: solr
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8080/solr/staging') %>
