development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://<%= ENV.fetch('REDIS_HOST', 'localhost') %>:<%= ENV.fetch('REDIS_PORT', 6379) %>

production:
  adapter: redis
  url: redis://<%= ENV.fetch('REDIS_HOST', 'localhost') %>:<%= ENV.fetch('REDIS_PORT', 6379) %>
