development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  # url: redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>
