development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('FEDORA_URL', 'http://localhost:8984/rest') %>
  base_path: /development
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('FEDORA_URL', 'http://localhost:8986/rest') %>
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('FEDORA_URL', 'http://localhost:8080/rest') %>
  base_path: /production
  request: { timeout: 1000, open_timeout: 1000}
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('FEDORA_URL', 'http://localhost:8080/rest') %>
  base_path: /staging
  request: { timeout: 1000, open_timeout: 1000}
