default: &default
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] %>
test:
  <<: *default
  base_path: /test
development:
  <<: *default
  base_path: /dev
staging:
  <<: *default
  base_path: /prod
production:
  <<: *default
  base_path: /prod
