default: &default
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('FEDORA_URL') %>
test:
  <<: *default
  base_path: /test
development:
  <<: *default
  base_path: /dev
production:
  <<: *default
  base_path: /prod
