development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] || 'http://localhost:8984' %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] || 'http://localhost:8986' %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /prod
