development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>

staging:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
