# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983' %>/solr/development-core
test:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8985' %>/solr/test-core
production:
  url: http://127.0.0.1:8983/solr/donut
