development:
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8983') %>/solr/development
test:
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8985') %>/solr/test
production:
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8080/solr/production') %>
staging:
  url: <%= ENV.fetch('SOLR_URL', 'http://localhost:8080/solr/staging') %>
