apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/kompose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: fcrepo
  name: fcrepo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fcrepo
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value:
                ' -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json"
                -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries" -Dfcrepo.home="/data/fedora"'
          image: ualbertalib/docker-fcrepo4:4.7
          name: fcrepo
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: fcrepo
      restartPolicy: Always
      volumes:
        - name: fcrepo
          persistentVolumeClaim:
            claimName: fcrepo
status: {}
