apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    built_by: od2
  creationTimestamp: null
  labels:
    io.kompose.service: memcache
  name: memcache
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: memcache
    spec:
      containers:
        - image: memcached
          name: memcache
          resources: {}
      restartPolicy: Always
status: {}
