apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/kompose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: solr
    spec:
      containers:
        - command:
            - bash
            - -c
            - /opt/solr/bin/solr -cloud -noprompt -f -p 8983
          image: solr:6-alpine
          name: solr
          resources: {}
          volumeMounts:
            - mountPath: /opt/solr/server/solr/mycores
              name: solr
      restartPolicy: Always
      volumes:
        - name: solr
          persistentVolumeClaim:
            claimName: solr
status: {}
