apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    built_by: od2
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
        - image: postgres:10
          name: db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
status: {}
