apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    built_by: od2
  creationTimestamp: null
  labels:
    io.kompose.service: workers
  name: workers
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: workers
    spec:
      containers:
        - args:
            - bash
            - -c
            - bundle exec sidekiq
          env:
            - name: ACTIVE_JOB_QUEUE_ADAPTER
              value: 'sidekiq'
            - name: DATABASE_URL
              value: 'postgresql://postgres@db.default.svc.cluster.local/postgres'
            - name: FEDORA_URL
              value: 'http://fcrepo.default.svc.cluster.local:8080/fcrepo/rest'
            - name: FITS_PATH
              value: '/opt/fits-1.0.5/fits.sh'
            - name: RAILS_CACHE_STORE_URL
              value: 'memcache.default.svc.cluster.local'
            - name: RAILS_ENV
              value: 'development'
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: REDIS_HOST
              value: 'redis.default.svc.cluster.local'
            - name: REDIS_PORT
              value: '6379'
            - name: SECRET_KEY_BASE
              value: 'asdf'
            - name: SOLR_URL
              value: 'http://solr.default.svc.cluster.local:8983/solr/development'
            - name: TRIPLESTORE_ADAPTER_TYPE
              value: 'blazegraph'
            - name: TRIPLESTORE_ADAPTER_URL
              value: 'http://blazegraph.default.svc.cluster.local:8080/bigdata/namespace/rw/sparql'
          image: od2_dev:latest
          name: workers
          resources: {}
          volumeMounts:
            - mountPath: /data/tmp/shared
              name: web-data-shared
            - mountPath: /data/public/branding
              name: web-data-branding
      restartPolicy: Always
      # Shared EFS disk for workers to access file uploads from web application
      volumes:
        - name: web-data-shared
          persistentVolumeClaim:
            claimName: web-data
        - name: web-data-branding
          persistentVolumeClaim:
            claimName: web-branding
status: {}
